-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Environment Variables

-- name: "Default"

-- -----------------------------------------------------

-- Default Settings in ml4w.conf
