-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--  _   _                  _                 _
-- | | | |_   _ _ __  _ __| | __ _ _ __   __| |
-- | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
-- |  _  | |_| | |_) | |  | | (_| | | | | (_| |
-- |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
--        |___/|_|
--
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Monitor
-- -----------------------------------------------------

require("conf/monitor")

-- -----------------------------------------------------
-- Cursor
-- -----------------------------------------------------

require("conf/cursor")

-- -----------------------------------------------------
-- Environment
-- -----------------------------------------------------

-- COMMENTED OUT BECAUSE its empty!
-- require("conf/environment")

-- -----------------------------------------------------
-- Keyboard
-- -----------------------------------------------------

require("conf/keyboard")

-- -----------------------------------------------------
-- Load color file
-- -----------------------------------------------------

require("colors")

-- -----------------------------------------------------
-- Autostart
-- -----------------------------------------------------

require("conf/autostart")

-- -----------------------------------------------------
-- Load configuration files
-- -----------------------------------------------------

require("conf/window")
require("conf/decoration")
require("conf/layout")

-- COMMENTED OUT BECAUSE its empty!
-- require("conf/workspace")

require("conf/misc")
require("conf/keybinding")

-- COMMENTED OUT BECAUSE its empty!
-- require("conf/windowrule")

-- -----------------------------------------------------

-- Animation

-- -----------------------------------------------------

require("conf/animation")

-- -----------------------------------------------------
-- Environment for xdg-desktop-portal-hyprland
-- -----------------------------------------------------


-- -----------------------------------------------------
-- ML4W Configuration
-- -----------------------------------------------------

require("conf/ml4w")


-- needed for steam games
hl.env("SDL_VIDEODRIVER", "wayland")

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
