-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = ~/.config/hypr/conf/environments/default.conf -> requires manual conversion
-- local default = require("default")
-- TODO: convert ~/.config/hypr/conf/environments/default.conf to .lua and use require()
