-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Keyboard Layout

-- https://wiki.hyprland.org/Configuring/Variables/#input

-- -----------------------------------------------------

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "grp:win_space_toggle",
        numlock_by_default = true,
        follow_mouse = 1,
        mouse_refocus = false,
        touchpad = {
            natural_scroll = false,
            scroll_factor = 1.0,
            -- Touchpad scroll factor
            disable_while_typing = false,
        },
        sensitivity = 0,
        -- Pointer speed: -1.0 - 1.0, 0 means no modification.
    },
})
